---
title: "HW5"
author: "Shirley Liang"
date: "2022-11-13"
output: github_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

### Problem 1

```{r}



```

### Problem 2

```{r, raw data, warning=FALSE}

homicides = read_csv("homicide-data.csv")

```

In the `homicides` dataset, there are `r nrow(homicides)` observations and `r ncol(homicides)` variables, including `r names(homicides)`.

```{r, raw and summary}

homicides <- homicides %>% 
  janitor::clean_names() %>% 
  mutate(city_state = str_c(city, state, sep = ","),
  disposition_status = case_when(disposition == "Closed without arrest" ~ "unsolved",
                     disposition == "Open/No arrest" ~ "unsolved",
                     disposition == "Closed by arrest" ~ "resolved")) 

summary <- homicides %>% group_by(city_state) %>% 
  summarize(total_number_of_homicides = n(), number_of_unsolved_homicides = sum(disposition_status == "unsolved")) 

summary

```

```{r, prop.test}
# Does it make sense to prop.test one city?
Baltimore_MD_proptest <- prop.test(summary %>% filter(city_state == "Baltimore,MD") %>% pull(number_of_unsolved_homicides), 
  summary %>% filter(city_state == "Baltimore,MD") %>% pull(total_number_of_homicides)) %>% 
  broom::tidy()

# Save the output of Baltimore,MD prop.test as an R object Baltimore_MD_proptest.

# Do prop.test for all cities
all_cities <- summary %>% mutate(prop_tests = map2(.x = number_of_unsolved_homicides, .y = total_number_of_homicides, ~ prop.test(x = .x, n = .y)),
  tidy_df = map(.x = prop_tests, ~ broom::tidy(.x))) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_df) %>% 
  select(city_state, estimate, conf.low, conf.high)

all_cities

```


### Problem 3

```{r}



```

